/* GWBasic.java */
/* Generated By:JavaCC: Do not edit this line. GWBasic.java */
package de.hft_stuttgart.cpl;

import java.io.InputStream;
import java.io.IOException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.Set;
import java.util.HashSet;
import java.util.List;
import java.util.ArrayList;
import java.util.Stack;
import java.util.TreeMap;

public class GWBasic implements GWBasicConstants {

    /* ---- book-keeping records ---- */
    public record WhileItem(String id, String startLabel, String endLabel) {}
    public record ForItem(String var, String topLabel, String endLabel,
                          String limVar, String stepVar) {}

    /* ---- transpiler state ---- */
    Set<Integer>      definedLines = new HashSet<>();   // every line number that exists in the program
    Stack<WhileItem>  whileStack   = new Stack<>();
    Stack<ForItem>    forStack     = new Stack<>();
    List<Integer>     gosubReturns = new ArrayList<>(); // one entry per GOSUB call site
    boolean           hasReturn    = false;
    int               nextId       = 0;                 // unique id for IF blocks
    int               gosubCounter = 0;                 // unique id for GOSUB return points
    int               forCounter   = 0;                 // unique id for FOR loops
    String            currentLine;

    /* self-imposed rule: a variable/array name may be at most this many
     * characters (a trailing '$' on a string name counts). A longer name is
     * rejected as a BASIC source error - it is NOT silently cut off. */
    static final int  MAX_NAME_LEN = 20;

    /* ============================================================
     *  main():
     *    1. read the whole .bas file
     *    2. bring all lines into strictly increasing numeric order
     *       (GW-BASIC Manual section 2.5 - line numbers define the
     *        order in which statements are stored / executed)
     *    3. remember which line numbers exist (for GOTO/GOSUB checks)
     *    4. feed the re-ordered source to the generated parser, capturing
     *       the generated C in a buffer
     *    5. on success, write  target/<name>.c
     *       on a BASIC source error, print a clear message and write the
     *       partial output to  target/<name>.c.error  (NOT a .c file, so a
     *       failed transpilation is easy to recognise).  The transpiler
     *       itself never throws - it only ever fails on bad BASIC input.
     * ============================================================ */
    public static void main(String[] args) {
        String base = "out";
        try {
            if (args.length > 0) {
                String n = new File(args[0]).getName();
                base = n.contains(".") ? n.substring(0, n.lastIndexOf('.')) : n;
            }

            InputStream raw;
            try {
                raw = (args.length == 0) ? System.in : new FileInputStream(args[0]);
            } catch (FileNotFoundException fnf) {
                System.err.println("ERROR: cannot open input file '" + args[0] + "'");
                System.exit(2);
                return;
            }

            BufferedReader br = new BufferedReader(new InputStreamReader(raw, StandardCharsets.UTF_8));
            TreeMap<Integer, String> program = new TreeMap<>();   // TreeMap -> ascending line order
            String ln;
            while ((ln = br.readLine()) != null) {
                String t = ln.trim();
                if (t.isEmpty()) continue;
                int sp = 0;
                while (sp < t.length() && Character.isDigit(t.charAt(sp))) sp++;
                if (sp == 0) {
                    System.err.printf("WARNING: line without a line number ignored: %s%n", t);
                    continue;
                }
                int num = Integer.parseInt(t.substring(0, sp));
                if (program.containsKey(num))
                    System.err.printf("WARNING: duplicate line number %d; later definition wins%n", num);
                program.put(num, t);
            }

            StringBuilder sorted = new StringBuilder();
            for (var e : program.entrySet()) sorted.append(e.getValue()).append('\n');

            GWBasic parser = new GWBasic(
                new ByteArrayInputStream(sorted.toString().getBytes(StandardCharsets.UTF_8)));
            parser.definedLines = new HashSet<>(program.keySet());

            /* capture all generated code so we can choose the file name afterwards */
            ByteArrayOutputStream buffer = new ByteArrayOutputStream();
            PrintStream realOut = System.out;
            PrintStream capture = new PrintStream(buffer, true, "UTF-8");
            boolean ok = true;
            String errMsg = null;
            System.setOut(capture);
            try {
                parser.parse();
            } catch (ParseException pe) {
                ok = false; errMsg = pe.getMessage();
            } catch (TokenMgrError te) {            /* JavaCC lexical error */
                ok = false; errMsg = te.getMessage();
            } catch (Throwable th) {                /* malformed program (e.g. NEXT without FOR) */
                ok = false; errMsg = (th.getMessage() != null) ? th.getMessage() : th.toString();
            } finally {
                System.out.flush();
                System.setOut(realOut);
            }

            File dir = new File("target");
            dir.mkdirs();
            if (ok) {
                File out = new File(dir, base + ".c");
                try (FileOutputStream fos = new FileOutputStream(out)) { fos.write(buffer.toByteArray()); }
                System.err.println("OK: transpiled successfully -> " + out.getPath());
            } else {
                File out = new File(dir, base + ".c.error");   /* extension is .error, not .c */
                try (FileOutputStream fos = new FileOutputStream(out)) { fos.write(buffer.toByteArray()); }
                System.err.println("ERROR in BASIC source: " + errMsg);
                System.err.println("Incomplete code written to " + out.getPath()
                                   + "  (extension is not .c -> transpilation did NOT succeed)");
                System.exit(1);
            }
        } catch (Exception ex) {
            /* should not happen for valid input; report cleanly instead of crashing */
            System.err.println("ERROR while transpiling: "
                               + (ex.getMessage() != null ? ex.getMessage() : ex.toString()));
            System.exit(2);
        }
    }

    /* emit an indented runtime call terminated with ';' */
    public void output(String format, Object... args) {
        System.out.printf("    ");
        System.out.printf(format, args);
        System.out.printf(";%n");
    }
    /* emit a C label */
    public void label(String format, Object... args) {
        System.out.printf("  ");
        System.out.printf(format, args);
        System.out.printf(":%n");
    }
    /* emit GOTO with target validation (undefined line -> runtime warning, never a C error) */
    public void emitGoto(String lineImage) {
        if (definedLines.contains(Integer.parseInt(lineImage)))
            output("JUMP(label_%s_init)", lineImage);
        else
            output("bad_line_number(%s)", lineImage);
    }
    /* enforce the maximum variable-name length; too long -> BASIC source error */
    public void checkName(String name) throws ParseException {
        if (name.length() > MAX_NAME_LEN)
            throw new ParseException("variable name '" + name + "' is too long: "
                + name.length() + " characters (the maximum allowed is " + MAX_NAME_LEN + ")");
    }

/* ===================== GRAMMAR ===================== */
  final public 
void parse() throws ParseException {
    prolog();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DEC_NUMBER:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      line();
    }
    epilog();
    jj_consume_token(0);
{if ("" != null) return;}
}

  final public void prolog() throws ParseException {
try {
            InputStream prologInput = getClass().getResourceAsStream("/prolog.c");
            prologInput.transferTo(System.out);
            prologInput.close();
        } catch (IOException e) {
            {if (true) throw new ParseException("Error loading prolog.c");}
        }
}

  final public void epilog() throws ParseException {
if (!whileStack.isEmpty()) {if (true) throw new ParseException("WHILE without WEND");}
        if (!forStack.isEmpty())   {if (true) throw new ParseException("FOR without NEXT");}

        /* jump over the GOSUB dispatcher that sits at the very end */
        output("JUMP(__prog_end)");

        /* dynamic RETURN dispatcher: maps a return-id back to its call site */
        if (!gosubReturns.isEmpty() || hasReturn) {
            label("__gosub_dispatch");
            System.out.println("    switch (gosub_pop()) {");
            for (int rid : gosubReturns)
                System.out.printf("      case %d: goto ret_%d;%n", rid, rid);
            System.out.println("      default: goto __prog_end;");
            System.out.println("    }");
        }

        try {
            InputStream epilogInput = getClass().getResourceAsStream("/epilog.c");
            epilogInput.transferTo(System.out);
            epilogInput.close();
        } catch (IOException e) {
            {if (true) throw new ParseException("Error loading epilog.c");}
        }
}

  final public void line() throws ParseException {Token number;
    number = jj_consume_token(DEC_NUMBER);
currentLine = number.image;
        label("label_%s_init", number.image);
    stmt();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COLON:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      jj_consume_token(COLON);
      stmt();
    }
label("label_%s_fini", number.image);
    jj_consume_token(EOL);
}

  final public void stmt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PRINT:{
      printStmt();
      break;
      }
    case WHILE:{
      whileStmt();
      break;
      }
    case WEND:{
      wendStmt();
      break;
      }
    case GOTO:{
      gotoStmt();
      break;
      }
    case GOSUB:{
      gosubStmt();
      break;
      }
    case RETURN:{
      returnStmt();
      break;
      }
    case IF:{
      ifStmt();
      break;
      }
    case FOR:{
      forStmt();
      break;
      }
    case NEXT:{
      nextStmt();
      break;
      }
    case DIM:{
      dimStmt();
      break;
      }
    case LET:
    case NAME:{
      letStmt();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void dimStmt() throws ParseException {Token id;
    jj_consume_token(DIM);
    id = jj_consume_token(NAME);
checkName(id.image);
    jj_consume_token(OPAREN);
    expr();
    jj_consume_token(CPAREN);
output("DIM_ARR(\"%s\")", id.image);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
      jj_consume_token(COMMA);
      id = jj_consume_token(NAME);
checkName(id.image);
      jj_consume_token(OPAREN);
      expr();
      jj_consume_token(CPAREN);
output("DIM_ARR(\"%s\")", id.image);
    }
}

  final public void printStmt() throws ParseException {int n = 0;   /* argument count - determined by the parser and passed to PRINT */

    jj_consume_token(PRINT);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPAREN:
    case PLUS:
    case MINUS:
    case NOT:
    case FLOAT_NUMBER:
    case DEC_NUMBER:
    case HEX_NUMBER:
    case OCT_NUMBER:
    case STRING:
    case NAME:{
      expr();
n++;
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:
        case SEMI:{
          ;
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          break label_4;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          jj_consume_token(COMMA);
          break;
          }
        case SEMI:{
          jj_consume_token(SEMI);
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        expr();
n++;
      }
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
output("PRINT(%d)", n);
}

  final public void letStmt() throws ParseException {Token id;
    boolean isArray = false;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LET:{
      jj_consume_token(LET);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    id = jj_consume_token(NAME);
checkName(id.image);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPAREN:{
      jj_consume_token(OPAREN);
      expr();
      jj_consume_token(CPAREN);
isArray = true;
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    jj_consume_token(EQUAL);
    expr();
if (isArray) output("STORE_ARR(\"%s\")", id.image);
        else         output("STORE(\"%s\")", id.image);
}

  final public void whileStmt() throws ParseException {
    jj_consume_token(WHILE);
String labelStart = "while_%s_start".formatted(currentLine);
        String labelEnd   = "while_%s_end".formatted(currentLine);
        whileStack.push(new WhileItem(currentLine, labelStart, labelEnd));
        label(labelStart);
    expr();
output("JUMP_IF_FALSE(%s)", "while_%s_end".formatted(currentLine));
}

  final public void wendStmt() throws ParseException {
    jj_consume_token(WEND);
if (whileStack.isEmpty()) {if (true) throw new ParseException("WEND without WHILE");}
        WhileItem item = whileStack.pop();
        output("JUMP(%s)", item.startLabel());
        label(item.endLabel());
}

  final public void gotoStmt() throws ParseException {Token n;
    jj_consume_token(GOTO);
    n = jj_consume_token(DEC_NUMBER);
emitGoto(n.image);
}

  final public void gosubStmt() throws ParseException {Token n;
    jj_consume_token(GOSUB);
    n = jj_consume_token(DEC_NUMBER);
if (definedLines.contains(Integer.parseInt(n.image))) {
            int rid = ++gosubCounter;
            gosubReturns.add(rid);
            output("gosub_push(%d)", rid);
            output("JUMP(label_%s_init)", n.image);
            label("ret_%d", rid);
        } else {
            output("bad_line_number(%s)", n.image);
        }
}

  final public void returnStmt() throws ParseException {
    jj_consume_token(RETURN);
hasReturn = true;
        output("JUMP(__gosub_dispatch)");
}

  final public void ifStmt() throws ParseException {int id;
    jj_consume_token(IF);
    expr();
id = ++nextId;
        output("JUMP_IF_FALSE(if_%d_else)", id);
    jj_consume_token(THEN);
    branchTarget();
output("JUMP(if_%d_end)", id);
        label("if_%d_else", id);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      branchTarget();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
label("if_%d_end", id);
}

/* the target of THEN / ELSE: either a line number (implicit GOTO) or a statement */
  final public void branchTarget() throws ParseException {Token n;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEC_NUMBER:{
      n = jj_consume_token(DEC_NUMBER);
emitGoto(n.image);
      break;
      }
    case PRINT:
    case LET:
    case WHILE:
    case WEND:
    case GOTO:
    case GOSUB:
    case RETURN:
    case IF:
    case FOR:
    case NEXT:
    case DIM:
    case NAME:{
      stmt();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void forStmt() throws ParseException {Token var;
    int id;
    String v, limv, stepv;
    jj_consume_token(FOR);
    var = jj_consume_token(NAME);
checkName(var.image);
        id    = ++forCounter;
        v     = var.image;
        limv  = "__lim_"  + id;
        stepv = "__step_" + id;
    jj_consume_token(EQUAL);
    expr();
output("STORE(\"%s\")", v);
    jj_consume_token(TO);
    expr();
output("STORE(\"%s\")", limv);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STEP:{
      jj_consume_token(STEP);
      expr();
output("STORE(\"%s\")", stepv);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
output("LOAD_CONST(1)"); output("STORE(\"%s\")", stepv);
    }
forStack.push(new ForItem(v, "for_" + id + "_top", "for_" + id + "_end", limv, stepv));
        label("for_%d_top", id);
        output("FOR_CONTINUE(\"%s\",\"%s\",\"%s\")", v, limv, stepv);
        output("JUMP_IF_FALSE(for_%d_end)", id);
}

  final public void nextStmt() throws ParseException {Token v = null;
    jj_consume_token(NEXT);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NAME:{
      v = jj_consume_token(NAME);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      ;
    }
if (forStack.isEmpty()) {if (true) throw new ParseException("NEXT without FOR");}
        ForItem f = forStack.pop();
        /* if NEXT names a variable, it must match the FOR it closes -> catches
         * mismatched / improperly nested loops (e.g. FOR I ... NEXT J). */
        if (v != null && !v.image.equals(f.var()))
            {if (true) throw new ParseException("NEXT " + v.image
                + " does not match the open FOR " + f.var());}
        output("STEP_VAR(\"%s\",\"%s\")", f.var(), f.stepVar());
        output("JUMP(%s)", f.topLabel());
        label(f.endLabel());
}

/* ---------- expression grammar (lowest -> highest precedence) ---------- */
  final public 
void expr() throws ParseException {
    orExpr();
}

  final public void orExpr() throws ParseException {
    andExpr();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_5;
      }
      jj_consume_token(OR);
      andExpr();
output("LOGIC_OR()");
    }
}

  final public void andExpr() throws ParseException {
    notExpr();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_6;
      }
      jj_consume_token(AND);
      notExpr();
output("LOGIC_AND()");
    }
}

  final public void notExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NOT:{
      jj_consume_token(NOT);
      relExpr();
output("LOGIC_NOT()");
      break;
      }
    case OPAREN:
    case PLUS:
    case MINUS:
    case FLOAT_NUMBER:
    case DEC_NUMBER:
    case HEX_NUMBER:
    case OCT_NUMBER:
    case STRING:
    case NAME:{
      relExpr();
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void relExpr() throws ParseException {
    addExpr();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQUAL:
      case NE:
      case LE:
      case GE:
      case LT:
      case GT:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQUAL:{
        jj_consume_token(EQUAL);
        addExpr();
output("CMP_EQ()");
        break;
        }
      case NE:{
        jj_consume_token(NE);
        addExpr();
output("CMP_NE()");
        break;
        }
      case LT:{
        jj_consume_token(LT);
        addExpr();
output("CMP_LT()");
        break;
        }
      case GT:{
        jj_consume_token(GT);
        addExpr();
output("CMP_GT()");
        break;
        }
      case LE:{
        jj_consume_token(LE);
        addExpr();
output("CMP_LE()");
        break;
        }
      case GE:{
        jj_consume_token(GE);
        addExpr();
output("CMP_GE()");
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void addExpr() throws ParseException {
    term();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        jj_consume_token(PLUS);
        term();
output("ADD()");
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
        term();
output("SUB()");
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void term() throws ParseException {
    fact();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIMES:
      case DIVIDE:
      case MODULO:{
        ;
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIMES:{
        jj_consume_token(TIMES);
        fact();
output("MUL()");
        break;
        }
      case DIVIDE:{
        jj_consume_token(DIVIDE);
        fact();
output("DIV()");
        break;
        }
      case MODULO:{
        jj_consume_token(MODULO);
        fact();
output("MOD()");
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void fact() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MINUS:{
      jj_consume_token(MINUS);
      fact();
output("NEG()");
      break;
      }
    case PLUS:{
      jj_consume_token(PLUS);
      fact();
      break;
      }
    case OPAREN:{
      jj_consume_token(OPAREN);
      expr();
      jj_consume_token(CPAREN);
      break;
      }
    case FLOAT_NUMBER:{
      t = jj_consume_token(FLOAT_NUMBER);
output("LOAD_CONST(%s)", t.image);
      break;
      }
    case DEC_NUMBER:{
      t = jj_consume_token(DEC_NUMBER);
output("LOAD_CONST(%s)", t.image);
      break;
      }
    case OCT_NUMBER:{
      t = jj_consume_token(OCT_NUMBER);
output("LOAD_CONST(%d)", Long.parseLong(t.image.substring(2), 8));
      break;
      }
    case HEX_NUMBER:{
      t = jj_consume_token(HEX_NUMBER);
output("LOAD_CONST(%d)", Long.parseLong(t.image.substring(2), 16));
      break;
      }
    case NAME:{
      t = jj_consume_token(NAME);
checkName(t.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPAREN:{
        jj_consume_token(OPAREN);
        expr();
        jj_consume_token(CPAREN);
String fn = t.image.toUpperCase();
              if      (fn.equals("SIN"))   output("SIN()");
              else if (fn.equals("COS"))   output("COS()");
              else if (fn.equals("CEIL"))  output("CEIL()");    /* round up   */
              else if (fn.equals("FLOOR")) output("FLOOR()");   /* round down */
              else if (fn.equals("INT"))   output("FLOOR()");   /* GW-BASIC INT = floor */
              else if (fn.equals("CHR$"))  output("CHR()");     /* code -> 1-char string */
              else if (fn.equals("STR$"))  output("STR()");     /* number -> its string  */
              else                         output("LOAD_ARR(\"%s\")", t.image);
        break;
        }
      default:
        jj_la1[22] = jj_gen;
output("LOAD_VAR(\"%s\")", t.image);
      }
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
output("LOAD_STR(%s)", t.image);
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  /** Generated Token Manager. */
  public GWBasicTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[24];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x4000,0xc9fe0000,0x8000,0x18000,0x18000,0x1a,0x40000,0x2,0x4000000,0xc9fe0000,0x20000000,0x0,0x0,0x0,0x1a,0x3f00,0x3f00,0x18,0x18,0xe0,0xe0,0x2,0x1a,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x10,0x0,0x100,0x0,0x0,0x0,0x1fc,0x0,0x0,0x0,0x110,0x0,0x100,0x2,0x1,0x1fc,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1f8,};
	}

  /** Constructor with InputStream. */
  public GWBasic(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public GWBasic(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new GWBasicTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public GWBasic(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new GWBasicTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new GWBasicTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public GWBasic(GWBasicTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(GWBasicTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[44];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 24; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 44; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
