/* Generated By:JavaCC: Do not edit this line. GWBasicConstants.java */
package de.hft_stuttgart.cpl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GWBasicConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPAREN = 1;
  /** RegularExpression Id. */
  int CPAREN = 2;
  /** RegularExpression Id. */
  int PLUS = 3;
  /** RegularExpression Id. */
  int MINUS = 4;
  /** RegularExpression Id. */
  int TIMES = 5;
  /** RegularExpression Id. */
  int DIVIDE = 6;
  /** RegularExpression Id. */
  int MODULO = 7;
  /** RegularExpression Id. */
  int EQUAL = 8;
  /** RegularExpression Id. */
  int NE = 9;
  /** RegularExpression Id. */
  int LE = 10;
  /** RegularExpression Id. */
  int GE = 11;
  /** RegularExpression Id. */
  int LT = 12;
  /** RegularExpression Id. */
  int GT = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int PRINT = 15;
  /** RegularExpression Id. */
  int LET = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int WEND = 18;
  /** RegularExpression Id. */
  int GOTO = 19;
  /** RegularExpression Id. */
  int GOSUB = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int THEN = 23;
  /** RegularExpression Id. */
  int ELSE = 24;
  /** RegularExpression Id. */
  int FOR = 25;
  /** RegularExpression Id. */
  int TO = 26;
  /** RegularExpression Id. */
  int STEP = 27;
  /** RegularExpression Id. */
  int NEXT = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int NOT = 31;
  /** RegularExpression Id. */
  int FLOAT_NUMBER = 32;
  /** RegularExpression Id. */
  int DEC_NUMBER = 33;
  /** RegularExpression Id. */
  int HEX_NUMBER = 34;
  /** RegularExpression Id. */
  int OCT_NUMBER = 35;
  /** RegularExpression Id. */
  int STRING = 36;
  /** RegularExpression Id. */
  int NAME = 37;
  /** RegularExpression Id. */
  int EOL = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"<>\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "\"PRINT\"",
    "\"LET\"",
    "\"WHILE\"",
    "\"WEND\"",
    "\"GOTO\"",
    "\"GOSUB\"",
    "\"RETURN\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"FOR\"",
    "\"TO\"",
    "\"STEP\"",
    "\"NEXT\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "<FLOAT_NUMBER>",
    "<DEC_NUMBER>",
    "<HEX_NUMBER>",
    "<OCT_NUMBER>",
    "<STRING>",
    "<NAME>",
    "<EOL>",
    "\" \"",
    "\"\\t\"",
  };

}
